app:
  test: 123
  scheduler:
    interval: 5000
  check-interval: 300
  database-access-type: jpa
  queue-name: tinkoff.edu.scrapperQueue
  exchange-name: tinkoffExchange
  use-queue: true
  bot-base-url: http://localhost:8081
  github-base-url: https://api.github.com
  stackoverflow-base-url: https://api.stackexchange.com/2.3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root

springdoc:
  swagger-ui:
    path: /swagger-ui
