app:
  test: 123
  scheduler:
    interval: 45000
  check-interval: 300
  database-access-type: jdbc
  queue-name: tinkoff.edu.scrapperQueue
  exchange-name: tinkoffExchange
  use-queue: true
  bot-base-url: http://localhost:8081
  github-base-url: https://api.github.com
  stackoverflow-base-url: https://api.stackexchange.com/2.3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root
  application:
    name: scrapper-app

management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure.include: [ "info", "health", "prometheus" ]
      path-mapping:
        prometheus: metrics
  endpoint:
    info.enabled: true
    health.enabled: true
    prometheus.enabled: true
  metrics.tags:
    application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui
