app:
  test: 123
  bot-token: ${BOT_TOKEN}
  api:
    scrapperBaseUrl: 'http://localhost:8080'
  queue-name: tinkoff.edu.scrapperQueue
  dead-letter-exchange-name: deadLetterTinkoffExchange

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1
  application:
    name: bot-app

management:
  server:
    port: 8091
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure.include: [ "info", "health", "prometheus" ]
      path-mapping:
        prometheus: metrics
  endpoint:
    info.enabled: true
    health.enabled: true
    prometheus.enabled: true
  metrics.tags:
    application: ${spring.application.name}

server:
  port: 8081
