/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chatId;
    private String linkUrl;

    public ChatLink() {}

    public ChatLink(ChatLink value) {
        this.chatId = value.chatId;
        this.linkUrl = value.linkUrl;
    }

    @ConstructorProperties({ "chatId", "linkUrl" })
    public ChatLink(
        @NotNull Long chatId,
        @NotNull String linkUrl
    ) {
        this.chatId = chatId;
        this.linkUrl = linkUrl;
    }

    /**
     * Getter for <code>public.chat_link.chat_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.chat_link.chat_id</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.chat_link.link_url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 2048)
    @NotNull
    public String getLinkUrl() {
        return this.linkUrl;
    }

    /**
     * Setter for <code>public.chat_link.link_url</code>.
     */
    public void setLinkUrl(@NotNull String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatLink other = (ChatLink) obj;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.linkUrl == null) {
            if (other.linkUrl != null)
                return false;
        }
        else if (!this.linkUrl.equals(other.linkUrl))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.linkUrl == null) ? 0 : this.linkUrl.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatLink (");

        sb.append(chatId);
        sb.append(", ").append(linkUrl);

        sb.append(")");
        return sb.toString();
    }
}
