/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private JSONB linkInfo;
    private OffsetDateTime lastCheckedAt;
    private OffsetDateTime updatedAt;

    public Link() {}

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.linkInfo = value.linkInfo;
        this.lastCheckedAt = value.lastCheckedAt;
        this.updatedAt = value.updatedAt;
    }

    @ConstructorProperties({ "id", "url", "linkInfo", "lastCheckedAt", "updatedAt" })
    public Link(
        @NotNull Long id,
        @NotNull String url,
        @NotNull JSONB linkInfo,
        @Nullable OffsetDateTime lastCheckedAt,
        @Nullable OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.url = url;
        this.linkInfo = linkInfo;
        this.lastCheckedAt = lastCheckedAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 2048)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.link.link_info</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public JSONB getLinkInfo() {
        return this.linkInfo;
    }

    /**
     * Setter for <code>public.link.link_info</code>.
     */
    public void setLinkInfo(@NotNull JSONB linkInfo) {
        this.linkInfo = linkInfo;
    }

    /**
     * Getter for <code>public.link.last_checked_at</code>.
     */
    @Nullable
    public OffsetDateTime getLastCheckedAt() {
        return this.lastCheckedAt;
    }

    /**
     * Setter for <code>public.link.last_checked_at</code>.
     */
    public void setLastCheckedAt(@Nullable OffsetDateTime lastCheckedAt) {
        this.lastCheckedAt = lastCheckedAt;
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.linkInfo == null) {
            if (other.linkInfo != null)
                return false;
        }
        else if (!this.linkInfo.equals(other.linkInfo))
            return false;
        if (this.lastCheckedAt == null) {
            if (other.lastCheckedAt != null)
                return false;
        }
        else if (!this.lastCheckedAt.equals(other.lastCheckedAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.linkInfo == null) ? 0 : this.linkInfo.hashCode());
        result = prime * result + ((this.lastCheckedAt == null) ? 0 : this.lastCheckedAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(linkInfo);
        sb.append(", ").append(lastCheckedAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
