app:
  test: 123
  scheduler:
    interval: 5000
  check-interval: 300
  database-access-type: jpa

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: root
    password: root

springdoc:
  swagger-ui:
    path: /swagger-ui
