name: build-bot-application
on:
  push:
    paths:
      - 'bot/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - run: mvn package -pl bot -am

      - name: scrapper dockerfile build
        run: docker build -f bot.Dockerfile -t ${{ secrets.GHCR_USERNAME }}/bot-app:latest .

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
          registry: ghcr.io
      - name: Push image
        run: docker push ${{ secrets.GHCR_USERNAME }}/bot-app:latest