name: build-bot-application
env:
  REPOSITORY: tinkoff-homeworks

on:
  push:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - run: mvn package -pl bot -am

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
          registry: ghcr.io

      - name: Build bot image
        run: docker build -f bot.Dockerfile -t ghcr.io/${{ github.actor }}/${{ env.REPOSITORY }}/bot-app:latest .

      - name: Push bot image
        run: docker push ghcr.io/${{ github.actor }}/${{ env.REPOSITORY }}/bot-app:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle run
        run: mvn -pl bot -am checkstyle:check
