name: build-scrapper-application
on:
  push:
    paths:
      - 'scrapper/**'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn package -e -X -pl scrapper -am

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build bot image
        run: docker build -f bot.Dockerfile -t ghcr.io/${{ github.actor }}/scrapper-app:latest .

      - name: Push bot image
        run: docker push ghcr.io/${{ github.actor }}/scrapper-app:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle run
        run: mvn -pl scrapper -am checkstyle:check
