name: build-scrapper-application
on:
  push:
    paths:
      - 'scrapper/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn package -pl scrapper -am

      - name: docker-build-scrapper
        run: docker build -f scrapper.Dockerfile -t ${{ secrets.GHCR_USERNAME }}/scrapper-app:latest .

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
          registry: ghcr.io

      - name: Push image
        run: docker push ${{ secrets.GHCR_USERNAME }}/scrapper-app:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle run
        run: mvn -pl scrapper -am checkstyle:check
